import React from 'react';
import {StyleSheet} from 'react-native';
import {PX} from '../pixel';
const styles = StyleSheet.create({
  mainView: {
    // position:'absolute',
    // top:0,

    width: '100%',
    height: PX(310),
    backgroundColor: '#000',
    borderBottomRightRadius: PX(35),
    borderBottomLeftRadius: PX(35),
    // justifyContent:'center',
    paddingBottom: '30%',
    alignItems: 'center',
  },
  from: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    paddingTop: '10%',
  },
  from1: {
    paddingTop: PX(15),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '90%',
  },
  text2: {
    fontSize: PX(13),
    color: '#ABA5A5',
    fontFamily: 'Montserrat-Regular',
  },
  text3: {
    fontSize: PX(15),
    color: '#F55800',
  },
  text1: {
    fontSize: PX(13),
    color: '#2D2D2D',
  },
  inputBox: {
    // paddingTop:PX(5),
    fontSize: PX(15),
    width: '100%',
    height: PX(40),
    color: '#000',
    fontFamily: 'Montserrat-Regular',
  },
  line: {
    flexDirection: 'row',
    paddingTop: PX(10),
    width: '100%',
    borderBottomWidth: 2,
    borderColor: '#C4C4C4',
  },
  line1: {
    flexDirection: 'row',
    paddingTop: PX(5),
    // width:'100%',
    borderBottomWidth: 2,
    borderColor: '#C4C4C4',
  },
  back: {
    width: PX(12.34),
    height: PX(21),
    tintColor: '#fff',
    // paddingLeft:'5%'
  },
  headerText2: {
    fontSize: PX(21),
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
  },
  header1: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // height:'15%',
    paddingTop: '15%',
  },
  email: {
    paddingTop: '10%',
    width: '90%',
  },
  text: {
    fontSize: PX(12),
    color: '#ABA5A5',
    fontFamily: 'Montserrat-Regular',
  },
  email1: {
    flexDirection: 'row',
    paddingTop: '5%',
    width: '100%',
    borderColor: '#C4C4C4',
    borderBottomWidth: 2,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: PX(10),
  },
  main: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  //   header:{paddingLeft:PX(100)},
  header2: {
    fontSize: PX(16),
    color: '#fff',
    paddingTop: '15%',
    // paddingRight: '35%',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'left',
    width: '88%',
  },
  btn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '87%',
    paddingTop: '7%',
  },
  visible: {
    fontSize: PX(15),
    paddingTop: '10%',
    paddingLeft: '5%',
    color: '#000',
    fontFamily: 'Montserrat-SemiBold',
  },
  visible1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingTop: '10%',
  },
  visible2: {
    width: '85%',
    resizeMode: 'contain',
    height: PX(178.72),
  },
  visible3: {
    color: '#F55800',
    fontSize: PX(15),
    paddingLeft: '5%',
    fontFamily: 'Montserrat-SemiBold',
  },
  defaultText: {
    color: '#F55800',
    fontSize: PX(15),
    fontFamily: 'Montserrat-SemiBold',
    marginLeft: PX(5),
  },
  visible4: {
    paddingVertical: PX(57),
    // paddingBottom: '17%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  visible5: {
    width: PX(350),
    height: PX(52),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F55800',
    borderRadius: PX(60),
  },
  visible6: {
    fontSize: PX(18),
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
  },
  redeem: {
    fontSize: PX(15),
    paddingTop: '10%',
    paddingLeft: '8%',
    color: '#000',
    fontFamily: 'Montserrat-SemiBold',
  },
  redeem1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingTop: '10%',
  },
  redeem2: {
    width: PX(356),
    height: PX(150),
  },
  redeem3: {
    paddingTop: PX(175),
    justifyContent: 'center',
    alignItems: 'center',
  },
  redeem4: {
    width: PX(350),
    height: PX(52),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F55800',
    borderRadius: PX(60),
  },
  redeem5: {
    fontSize: PX(18),
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
  },
  gift: {
    fontSize: PX(15),
    paddingTop: PX(30),
    paddingLeft: '8%',
    color: '#000',
    fontFamily: 'Montserrat-SemiBold',
  },
  gift1: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingTop: PX(20),
  },
  gift2: {
    width: '85%',
    height: PX(180),
    resizeMode: 'contain',
  },
  gift3: {
    color: '#F55800',
    fontSize: PX(15),
    paddingLeft: '8%',
    paddingTop: PX(35),
    fontFamily: 'Montserrat-SemiBold',
  },
  gift4: {
    paddingTop: PX(120),
    justifyContent: 'center',
    alignItems: 'center',
  },
  gift5: {
    width: PX(350),
    height: PX(52),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F55800',
    borderRadius: PX(60),
  },
  gift6: {
    fontSize: PX(18),
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
  },
  from2: {
    width: '75%',
    height: PX(160),
  },
  from3: {
    width: '98%',
    alignItems: 'center',
  },
  icon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  icon1: {
    width: PX(18),
    height: PX(18),
    marginRight: PX(10),
    resizeMode: 'contain',
  },
  icon2: {
    width: '100%',
    height: PX(40),
    fontSize: PX(15.41),
    fontFamily: 'Montserrat-Regular',
    color: '#2D2D2D',
  },
  icon3: {
    width: PX(16.5),
    height: PX(12),
    tintColor: '#000',
    marginRight: PX(10),
    resizeMode: 'contain',
  },
  btn1: {
    paddingTop: PX(70),
    justifyContent: 'center',
    alignItems: 'center',
  },
  btn2: {
    width: PX(350),
    height: PX(52),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F55800',
    borderRadius: PX(60),
  },
  btnText: {
    fontSize: PX(18),
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
  },
});
export default styles;
